name: Upstream Sync
on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点执行
  workflow_dispatch:     # 支持手动触发
permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Fork
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: cmliu/edgetunnel   # 如：HackJava/HackJava
          upstream_sync_branch: main           # 上游分支
          target_sync_branch: main             # 你的分支
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
